name: ファイルダウンロードとGitHub Pagesへのデプロイ

on:
  # schedule:
  #   - cron: '0 0 */10 * *' # 1日1回 UTCでの10時に
  workflow_dispatch:  # 手動トリガー

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v2

      - name: ダウンロード対象ファイルの取得
        run: |
          mkdir -p data/org  # ダウンロード先のディレクトリを作成
          curl -L "https://www.city.kumamoto.jp/opendata/pub/Insyokutenneigyoukyoka.csv" -o data/org/Insyokutenneigyoukyoka.csv

      - name: GitHub Pagesへデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data  # GitHub Pagesにデプロイするディレクトリを指定
          # publish_dirはダウンロードしたファイルがあるディレクトリに設定してください
          publish_branch: gh-pages
